# Generated by Django 5.2.12 on 2026-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_rename_user_complaint_complainant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер владельца'),
        ),
    ]
